name: notice

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: Dry run
        default: true

jobs:
  publish_npm:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm pack
        id: pack
        run: |
          if [ ${{ inputs.dry_run == true }} ]; then
            echo "> [!NOTE]"  >> $GITHUB_STEP_SUMMARY
            echo "> Dry mode enabled, package will not be published to npm" >> $GITHUB_STEP_SUMMARY
          fi
          echo "```bash" >> $GITHUB_STEP_SUMMARY
          # Redirect the stderr to the summary so we can see the package output easier
          FILE_PATH=$(npm pack 2>> $GITHUB_STEP_SUMMARY)
          echo "```" >> $GITHUB_STEP_SUMMARY

          echo "FILE_PATH=${FILE_PATH}" >> $GITHUB_OUTPUT
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{steps.pack.outputs.FILE_PATH}}
          archive: false # already archived
      - name: publish
        run: npm publish ${{ inputs.dry_run == true && '--dry-run' || '' }}

