name: 'RELEASE: npm publish'

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
