name: Reusable Prepare NPM for Publish

on:
  workflow_call:

jobs:
  prepare_npm_for_publish:
    runs-on: ubuntu-latest
    name: Prepare npm 

    steps:
      - uses: actions/checkout@v4

      # - name: Fail the action
      #   run: exit 1

      - name: Run a one-line script
        run: echo Preparing npm ready for publish to dry run or the real npm registry