name: 'RELEASE: publish to npm and GitHub Releases'

on:
  workflow_dispatch:

jobs:
  build_release:
    name: Build the release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo BUILD THE RELEASE
  npm:
    needs: [build_release]
    name: Publish to npm
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Fail the action
        run: exit 1

      - name: Run a one-line script
        run: echo PUBLISH TO NPM
  github_releases:
    needs: [npm] # Ensure that this job only runs if npm succeeds
    name: Publish to GitHub Releases
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo PUBLISH TO GitHub Releases
