name: 'RELEASE: publish to npm and GitHub Releases'

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: dry run?
        default: true

jobs:
  prepare_npm:
    name: Prepare npm 
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # - name: Fail the action
      #   run: exit 1

      - name: Run a one-line script
        run: echo PUBLISH TO NPM
  dry_run_npm:
    if: inputs.dry_run == true
    needs: [prepare_npm]
    name: Dry run npm
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Fail the action
        run: exit 1

      - name: Run a one-line script
        run: echo DRY RUN TO NPM
  publish_to_npm:
    if: inputs.dry_run == false
    needs: [prepare_npm]
    name: Publish to npm
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Fail the action
        run: exit 1

      - name: Run a one-line script
        run: echo DRY RUN TO NPM
  prepare_github_release:
    needs: [publish_to_npm, dry_run_npm]
    name: Prepare Github Release 
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # - name: Fail the action
      #   run: exit 1

      - name: Run a one-line script
        run: echo PUBLISH TO NPM
  dry_run_github_release:
    if: inputs.dry_run == true
    needs: [prepare_github_release]
    name: Dry Run GitHub Releases
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo DRY RUN GitHub Releases
  publish_to_github_release:
    if: inputs.dry_run == false
    needs: [prepare_github_release]
    name: Publish to GitHub Releases
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo PUBLISH TO GitHub Releases

