name: Publish using 'uses' with actions

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: dry run?
        default: true

jobs:
  prepare_npm_for_publish:
    uses: ./.github/workflows/prepare-npm-for-publish.yml
  publish:
    runs-on: ubuntu-latest
    needs: [prepare_npm_for_publish]
    steps:
      - uses: actions/checkout@v4
      - name: Dry run
        if: inputs.dry_run == true
        uses: ./.github/actions/publish-npm-dry-run
      - name: Dry run
        if: inputs.dry_run == false
        uses: ./.github/actions/publish-npm