name: Npm Publish

on:
  workflow_call:

jobs:
  dry_run_npm_publish:
    runs-on: ubuntu-latest
    name: publish npm 

    steps:
      - uses: actions/checkout@v4

      # - name: Fail the action
      #   run: exit 1

      - name: Run a one-line script
        run: echo npm publish