name: 'RELEASE: publish to npm and GitHub Releases'

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: dry run?
        default: true

jobs:
  build_release:
    name: Build the release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo BUILD THE RELEASE
  prepare_npm:
    needs: [build_release]
    name: Prepare npm 
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Fail the action
        run: exit 1

      - name: Run a one-line script
        run: echo PUBLISH TO NPM
  dry_run_npm:
    if: inputs.dry_run == true
    needs: [prepare_npm]
    name: Dry run npm
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Fail the action
        run: exit 1

      - name: Run a one-line script
        run: echo DRY RUN TO NPM
  publish_to_npm:
    if: inputs.dry_run == false
    needs: [prepare_npm]
    name: Publish to npm
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Fail the action
        run: exit 1

      - name: Run a one-line script
        run: echo DRY RUN TO NPM
  github_releases:
    needs: [dry_run_npm, publish_to_npm] # Ensure that this job only runs if npm succeeds
    name: Publish to GitHub Releases
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo PUBLISH TO GitHub Releases

