name: 'RELEASE: npm publish'
run-name: "RELEASE: npm publish${{ inputs.dry_run && '( Dry run)' || '' }}"

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: Dry run
        default: true

env:
  DRY_RUN: inputs.dry_run == true
  PRODUCTION_RUN: inputs.dry_run == false

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do some prep for npm
        run: echo Preparing npm ready for publish to dry run or the real npm registry
      - name: Dry run
        if: inputs.dry_run == true
        uses: ./.github/actions/publish-npm-dry-run
      - name: Real publish
        if: inputs.dry_run == false
        uses: ./.github/actions/publish-npm
  publish_github_release:
    runs-on: ubuntu-latest
    needs: [publish_npm]
    steps:
      - uses: actions/checkout@v4
      - name: Do some prep for github
        run: echo prepare some stuff ready for real or dry github release
      - name: Dry run
        if: ${DRY_RUN}
        uses: ./.github/actions/publish-npm-dry-run
      - name: Real publish
        if: ${PRODUCTION_RUN}
        uses: ./.github/actions/publish-npm